### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by o-dka** [jez9999/gooeycarboncopy#11]
I couldn't reach you on your [gitlab](https://gitlab.com/jez9999/vsclassic-icon-theme/-/issues/2) for a few weeks.\
So I am here now!

I am here to ask permission to fork your fantastic [vsclassic-icon-theme](https://gitlab.com/jez9999/vsclassic-icon-theme), and make it downloadable to [Vscodium](https://vscodium.com). Vscodium doesn't support  regular Vscode marketplace due to [legal stuff](https://github.com/VSCodium/vscodium#extensions-and-the-marketplace), so instead they use [open-vsx.org](open-vsx.org) for downloadable extensions.  \
The only way to download this icon theme right now is to download .vsix  file, open it with a command pallet and navigate to the .vsix file directory. Which is annoying to do if you want to have the same feeling environment on multiple machines.\

So I thought about hosting it on open-vsx myself , but I do feel obliged to ask your permission first. \
I hope you will contact me as soon as possible regarding this.
-With best wishes  
o-dka

**Comment by jez9999** [comment]
Hi,

No problem - could you give credit for the original theme somewhere though please?

**Comment by o-dka** [comment]
sure, will do!

**Comment by o-dka** [comment]
Can I add you as a co-owner of the repo?

**Comment by jez9999** [comment]
If you want.

**Comment by o-dka** [comment]
Ok, I did
